name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (for multi-platform builds, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub (optional, if pushing to Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.event_name != 'pull_request'  # Only log in on push or manual trigger

      # Step 4: Log in to GitHub Container Registry (optional, alternative to Docker Hub)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'

      # Step 5: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}  # Push only on push/manual, not PR
          tags: |
            ${{ github.repository_owner }}/compar:latest
            ghcr.io/${{ github.repository_owner }}/compar:latest
          # Optional: Add build args or platforms if needed
          # platforms: linux/amd64,linux/arm64
          # build-args: |
          #   VERSION=1.0

      # Step 6: Test the Docker image (optional)
      - name: Test Docker image
        run: |
          docker run --rm ${{ github.repository_owner }}/compar:latest /bin/bash -c "source /opt/conda/etc/profile.d/conda.sh && conda env list"